{
    parserClass="com.github.czy211.wowtoc.parser.TocParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Toc"
    psiImplClassSuffix="Impl"
    psiPackage="com.github.czy211.wowtoc.psi"
    psiImplPackage="com.github.czy211.wowtoc.psi.impl"

    elementTypeHolderClass="com.github.czy211.wowtoc.psi.TocTypes"
    elementTypeClass="com.github.czy211.wowtoc.psi.TocElementType"
    tokenTypeClass="com.github.czy211.wowtoc.psi.TocTokenType"

    psiImplUtilClass="com.github.czy211.wowtoc.psi.impl.TocPsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (tag|refer|COMMENT|CRLF)

tag ::= TAG_PREFIX TAG_NAME SEPARATOR TAG_VALUE {methods=[getTagName getTagNameRange]}

refer ::= FILE_NAME {methods=[getFileName getFileNameRange]}
